services:
  web:
    build: .
    command:  sh -c "poetry run python teams_py/manage.py migrate &&
             poetry run python teams_py/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./data/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1